# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  #secret_key_base: b63eef056dfc72062bd8faa424a7b8113b5f0a605b88ed4cd1dcf623fa9b36c44e4d4e0faa02d057d26e3672a1d3e0f1a7dabeb00dbe6592f29daf4540c0453d
  secret_key_base: 1f9f3e703647bf39e98162b1d4dc8cd67d51cbe1f95153b7147219d1b944f07503f6c0ad3b027492be3fc792875fa523f671abae209da272018d8bd0fd68cf24
  #rakuten_application_id: <%= ENV["RAKUTEN_APPLICATION_ID"] %>
  #rakuten_affiliate_id: <%= ENV["RAKUTEN_AFFILIATE_ID"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  associate_tag: <%= ENV["ASSOCIATE_TAG"] %>

test:
  #secret_key_base: fe7fa433e102ed342d0b94dd840a02b3fa8009e83bee74a1e4ab7f2fa3e7e9e279991bb5de92385b648f9f2778796e97dbc9f54841efd9332ad7cd6d8c88089e
  secret_key_base: c4cc3783df352ea33aa999af6319f04948b8dc06b51045edc990024a379dcbd8f55d91ab17c09de39c29efbfabdd120d01259777f72173aac417fa6a427faba1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  #rakuten_application_id: <%= ENV["RAKUTEN_APPLICATION_ID"] %>
  #rakuten_affiliate_id: <%= ENV["RAKUTEN_AFFILIATE_ID"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  associate_tag: <%= ENV["ASSOCIATE_TAG"] %>